name: "Merge release branch to master"

on: 
  pull_request:
    branches: 
      - master
    types:
      - opened
      - labeled

jobs:
  merge-to-master:
    name: Merge release branch
    runs-on: ubuntu-latest
    steps:
      - name: Merge pull request
      - uses: actions/checkout@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git checkout master
          gh pr merge release --merge
