name: "Merge rebase"
on: issue_comment

jobs:
  merge-rebase:
    if: ${{ github.event.issue.pull_request && startsWith( github.event.comment.body , '/merge develop') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        id: get-pr
        with:
          script: |
            const request = {
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            }
            core.info(`Getting PR #${request.pull_number} from ${request.owner}/${request.repo}`)
            try {
              const result = await github.pulls.get(request)
              return result.data
            } catch (err) {
              core.setFailed(`Request failed with error ${err}`)
            }

      - uses: actions/checkout@v2
        with:
          ref: ${{ fromJSON(steps.get-pr.outputs.result).head.ref }}
          fetch-depth: 0
          
      - uses: fregante/setup-git-token@v1
        with:
          token: ${{ secrets.BOT_TOKEN }}
          name: "isaranto-bot "
          email: prcg1@thebeat.co
    
#       - name: Initialize mandatory git config
#         run: |
#           git config user.name "GitHub actions"
#           git config user.email noreply@github.com
#           git config --global push.default current

      - name: Merge PR
        if: github.event.issue.pull_request
        env:
          BRANCH_NAME: ${{ fromJSON(steps.get-pr.outputs.result).head.ref }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git merge --no-ff -m "Merge develop into this branch" develop
          git push origin
