name: Open - Approve PR
on: workflow_dispatch

jobs:
#   create-new-release:
#     name: "Create release branch + Bump Version"
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2

#       # In order to make a commit, we need to initialize a user.
#       # You may choose to write something less generic here if you want, it doesn't matter functionality wise.
#       - name: Initialize mandatory git config
#         run: |
#           git config user.name "GitHub actions"
#           git config user.email noreply@github.com
#       # This step will differ depending on your project setup
#       # Fortunately, yarn has a built-in command for doing this!
#       - name: Bump version in package.json
#         run: |
#           yarn version --minor --no-git-tag-version
#           VERSION=$(jq -r .version package.json)
#           echo "RELEASE_VERSION=$VERSION" >> $GITHUB_ENV
      
#       - name: Create release branch
#         run: git checkout -b release/${{ env.RELEASE_VERSION }}
      
#       - name: Commit changelog and manifest files
#         id: make-commit
#         run: |
#           git add package.json
#           git commit --message "Prepare release ${{ env.RELEASE_VERSION }}"
#           echo "::set-output name=commit::$(git rev-parse HEAD)"
      
#       - name: Push new branch
#         run: git push origin release/${{ env.RELEASE_VERSION }}
      
#       - name: Create pull request release -> master
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         run: |
#           body="Hi @${{ github.actor }}! \n This PR was created in response to a manual trigger of the release workflow here:\
#           https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}. \n \
#           I've updated the changelog and bumped the versions in the manifest files in this commit: ${{ steps.make-commit.outputs.commit }}. \n \
#           Merging this PR will create a GitHub release and upload any assets that are created as part of the release build."
#           gh pr create --title "${{ env.RELEASE_VERSION }}" --body "$body" --label release --base master --head release/${{ env.RELEASE_VERSION }} 
          
  open-pr:
    name: "Approve PR"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Initialize mandatory git config
        run: |
          git config user.name "GitHub actions"
          git config user.email noreply@github.com
      
      - name: Merge pull request
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: |
          gh pr review master --approve
          gh pr merge release/2.1.0 --delete-branch --merge
