name: Create PR
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The version you want to release.'
        required: true
        
jobs:
  draft-new-release:
    name: "Draft a new release"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create release branch
        run: git checkout -b release/${{ github.event.inputs.version }}

      # In order to make a commit, we need to initialize a user.
      # You may choose to write something less generic here if you want, it doesn't matter functionality wise.
      - name: Initialize mandatory git config
        run: |
          git config user.name "GitHub actions"
          git config user.email noreply@github.com
      # This step will differ depending on your project setup
      # Fortunately, yarn has a built-in command for doing this!
      - name: Bump version in package.json
        run: |
          yarn version --new-version ${{ github.event.inputs.version }} --no-git-tag-version
      - name: Commit changelog and manifest files
        id: make-commit
        run: |
          git add package.json
          git commit --message "Prepare release ${{ github.event.inputs.version }}"
          echo "::set-output name=commit::$(git rev-parse HEAD)"
      - name: Push new branch
        run: git push origin release/${{ github.event.inputs.version }}
      
      - name: Create pull request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          body="Hi @${{ github.actor }}! \n This PR was created in response to a manual trigger of the release workflow here:\
          https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}. \n \
          I've updated the changelog and bumped the versions in the manifest files in this commit: ${{ steps.make-commit.outputs.commit }}. \n \
          Merging this PR will create a GitHub release and upload any assets that are created as part of the release build."
          gh pr create --title "The bug is fixed" --body "$body" --label gitflow --base master --head release/${{ github.event.inputs.version }}
